services:
  web:
    container_name: proxitok-web
    #image: ghcr.io/pablouser1/proxitok:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok-redis
      - REDIS_PORT=6379
      - API_CHROMEDRIVER=http://proxitok-chromedriver:9515
      # - API_VERIFYFP=verify_...
      # - API_DEVICE_ID=4586...
    labels:
      - "io.containers.autoupdate=registry"
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - redis
      - chromedriver
    networks:
      - proxitok
    security_opt:
      - no-new-privileges:true
    #cap_drop:
    #  - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
  # Redis, used for caching
  redis:
    container_name: proxitok-redis
    image: docker.io/library/redis:7.4-alpine
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=registry"
    networks:
      - proxitok
    init: true
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  # Chromedriver instance, used for sending requests to TikTok
  chromedriver:
    container_name: proxitok-chromedriver
    image: zenika/alpine-chrome:with-chromedriver
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    shm_size: 1g
    networks:
      - proxitok
    security_opt:
      - seccomp:./misc/setup/docker/chrome.json
volumes:
  proxitok-cache:

networks:
  proxitok:
